# The service providing the commit statuses to GitHub.
status = ["buildbot/yk-buildbot-build-script-hw"]

# Allow 60 minutes for build + tests
timeout_sec = 3600

# Have bors delete auto-merged branches
delete_merged_branches = true

cut_body_after = ""
